name = "EtherArrays"
uuid = "73c2380e-57df-4bce-8a8d-9b9b8436c78c"
authors = ["ChenyuBao <chenyu.bao@outlook.com>"]
version = "0.1.0"

[deps]
EtherMaths = "e9131f1e-6ff8-4b70-992e-15574141dedc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
EtherMaths = "0.1.2"
StaticArrays = ">=1.9.15"
StaticArraysCore = ">=1.4.4"
Test = ">=1.11.0"
